### ISSUE TITLE
Something went wrong when applying the model

### ISSUE THREAD

**Issue by clee630** [MarvinLvn/voice-type-classifier#26]
Hello, 
I get this error when I apply the model to my wav file. Would you happen to know why?

Thank you.
![Screenshot 2023-01-25 at 10 32 36 AM](https://user-images.githubusercontent.com/119370992/214605459-c3b8f8bd-8d59-45d2-9721-a308a6f219f1.png)

**Comment by MarvinLvn** [comment]
Hello @clee630  !

Found the bug! You encounter this bug because the folder from which you're trying to apply the model contains a space.

Here, my current folder is `voice_type_classifier AirTek` --> the error is raised.

![Screenshot from 2023-01-28 17-38-28](https://user-images.githubusercontent.com/11290637/215278213-6307465a-bf21-4388-88a9-6759ee6f0ab2.png)

Here, it is `voice_type_classifier_AirTek` --> the issue disappears.

![Screenshot from 2023-01-28 17-41-23](https://user-images.githubusercontent.com/11290637/215278333-3366fcd3-6b12-4609-96ec-28c42f3a809b.png)

I strongly recommend avoiding the use of spaces in folder/file names as they are not supported by all operating systems or command lines. See [this documentation]( https://instr.iastate.libguides.com/datashare/filenames)

Cheers!
