### ISSUE TITLE
problem validating after retraining (err: ALICE/21)

### ISSUE THREAD

**Issue by giodesp** [MarvinLvn/voice-type-classifier#27]
Hi, 
I have finished training using _pyannote-audio mlt train_ and am now running the validation on my development set with command:
__pyannote-audio mlt validate <path/to/train> MyProject.SpeakerDiarization.MyProtocol_

Initially, I ran out of CUDA memory but specifying --batch=16 seemed to fix this. I am now receiving an error message which links me to https://github.com/orasanen/alice/issues/21.
I tried creating a new env with the updated ALICE.yml from the solution of that page's error but this didn't solve my issue.

I am on an Ubuntu machine. 

Any help would be greatly appreciated :)

**Comment by MarvinLvn** [comment]
Hi @giodesp,

Yep! 

Solution 1:
In `labels_detection.py` you can uncomment lines 42 to 45 , comment line 156 and uncomment lines 157 to 164, this should fixed your issue. You might need to run a `pip install pyannote.metrics==2.3` within the pyannote env too.

Solution 2:
Assuming you are in the `voice_type_classifier` folder:

```
git checkout 5016d50000cc6a8ccb7d213744ccc817bcd66c27
cd pyannote-audio
git checkout 656997ca98265409b816582b4d1811b76dce4fe5
```
But you'll need to reinstall the environment

The error is due to a compatibility error we've met with MAC systems that I couldn't solve! 
Following solution 1 or 2 just reverts the code back :)

Cheers!

**Comment by giodesp** [comment]
Hi @MarvinLvn,

Thanks so much for the assistance on this!
I tried both solutions, which did stop me receiving the ALICE/21 error. 

However, I am still stuck when validating (_0iteration [00:00, ?iteration/s]_).
Perhaps I should open a new issue for this... but if you have any ideas about what might be preventing the validation from getting off the ground, please let know.

To clarify, I am using the command _pyannote-audio mlt validate --batch=16 voice_type_classifier/MyProject/audio/train/MyProject.SpeakerDiarization.MyProtocol.train/ MyProject.SpeakerDiarization.MyProtocol --gpu_ on Ubuntu 20.04.

Thanks again.

**Comment by MarvinLvn** [comment]
Validation may take some time ! Can you try to wait a bit longer and see if the script makes any progress?

**Comment by giodesp** [comment]
Yes, of course! Sorry, didn't mean to be impatient, I was just concerned because when training I always received some signs of progress. Anyway, fingers crossed it's doing something and I'll get back to you later if nothing changes.

UPDATE: As you suggested, I just needed to wait, it's validating now, thank you :)
